# Use root/12346 as user/password credentials

version: '2'

services:
    mysql:
        image: mysql
        container_name: demomysql
        restart: always
        ports:
            - 3317:3306
        volumes:
            - ./conf:/etc/mysql/conf.d  # 配置文件
            - ./data:/var/lib/mysql # 数据存储
            - ./logs:/var/log/mysql # 日志
        environment:
            MYSQL_ROOT_PASSWORD: 123456
    mysql_admin:   
        image: daocloud.io/daocloud/phpmyadmin:edge 
        container_name: demomysql_admin        
        privileged: false   
        restart: always   
        links:
            - mysql:db
        ports:   
            - '10081:80'   
        environment:   
            - PMA_PORT=3306   
            - PMA_HOST=db